name: angular-common-template

on:
  workflow_call:
    inputs:
      NodeJS-version:
        required: true
        type: string
      environment:
        required: true
        type: string
      publish_dir:
        required: true
        type: string  
      enable_jekyll:
        required: true
        type: string
      output:
        required: true
        type: string
      format:  
        required: true
        type: string
      code-quality-check:  
        required: true
        type: string    
jobs:
  angular-common-workflow:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ' ${{ inputs.NodeJS-version }}'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm run test:headless
      
    - name: Build
      run: npm run build:${{ inputs.environment }}

    -  name: code analysis   
       if: ${{ inputs.code-quality-check  == 'yes' }}
       uses: codacy/codacy-analysis-cli-action@master
       with:
        output: ${{ inputs.output }}
        format: ${{ inputs.format }}
          # Adjust severity of non-security issues
        gh-code-scanning-compat: true
          # Force 0 exit code to allow SARIF file generation
          # This will hand over control about PR rejection to the GitHub side
        max-allowed-issues: 2147483647
      
      # Upload the SARIF file generated in the previous step
    -  name: Upload SARIF results file
       if: ${{ inputs.code-quality-check  == 'yes' }}
       uses: github/codeql-action/upload-sarif@main
       with:
        sarif_file: ${{ inputs.output }}   
      
    - name: Deploy
      if: success()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ${{ inputs.publish_dir }}
        enable_jekyll: ${{ inputs.enable_jekyll }}
